# This file may be used to create an environment using:
# conda env create -f environment.yml
name: wikirepo-dev
channels:
  - anaconda
  - conda-forge
  - defaults

# Also needs wikidata
dependencies:
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - python-dateutil
  - tqdm
